# Generated by Django 3.0.2 on 2020-02-24 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Suggestions.Algorithm', to_field='name'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='study_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Suggestions.Study', to_field='name'),
        ),
    ]
