# Generated by Django 3.0.2 on 2020-03-01 17:47

import API.choices
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(blank=True, default='AVAILABLE', max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('objective', models.IntegerField(choices=[('MAXIMIZE', 1), ('MINIMIZE', 2)], default=API.choices.OBJECTIVE['MINIMIZE'])),
                ('status', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Algorithm', to_field='name')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Metric', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='TrialMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_id', models.IntegerField()),
                ('training_step', models.IntegerField(blank=True, null=True)),
                ('objective_value', models.FloatField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('parameter_values', models.TextField(blank=True, null=True)),
                ('training_step', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('study_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Study', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.IntegerField(choices=[('DISCRETE', 1), ('CATEGORICAL', 2), ('DOUBLE', 3), ('INTEGER', 4)], default=API.choices.TYPE['CATEGORICAL'])),
                ('values', models.TextField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Study', to_field='name')),
            ],
        ),
    ]
