# Generated by Django 3.0.2 on 2020-03-16 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=128, unique=True)),
                ('status', models.CharField(blank=True, default='AVAILABLE', max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=128, unique=True)),
                ('type', models.SlugField(max_length=128)),
                ('status', models.CharField(blank=True, default='AVAILABLE', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=128, unique=True)),
                ('status', models.CharField(default='AVAILABLE', max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('datasets', models.ManyToManyField(blank=True, related_name='datasets', to='API.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=128, unique=True)),
                ('runs', models.IntegerField(default=10)),
                ('num_suggestions', models.IntegerField(default=10)),
                ('dataset', models.CharField(default='iris', max_length=128)),
                ('status', models.CharField(default='PENDING', max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('algorithm', models.ForeignKey(default='RandomSearch', on_delete=django.db.models.deletion.CASCADE, to='API.Algorithm', to_field='name')),
                ('metric', models.ForeignKey(default='SimpleFunction', on_delete=django.db.models.deletion.CASCADE, to='API.Metric', to_field='name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField(blank=True, null=True)),
                ('training_step', models.IntegerField(blank=True, default=0, null=True)),
                ('score', models.FloatField(blank=True, default=0, null=True)),
                ('score_info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped')], max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Study', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=128)),
                ('type', models.CharField(choices=[('DISCRETE', 'Discrete'), ('CATEGORICAL', 'Categorical'), ('FLOAT', 'Float'), ('INTEGER', 'Integer')], max_length=128)),
                ('values', models.TextField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Study', to_field='name')),
            ],
        ),
    ]
