# Generated by Django 3.0.2 on 2020-03-02 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metric',
            name='status',
            field=models.CharField(default='AVAILABLE', max_length=128),
        ),
        migrations.AlterField(
            model_name='study',
            name='algorithm',
            field=models.ForeignKey(default='RandomSearch', on_delete=django.db.models.deletion.CASCADE, to='API.Algorithm', to_field='name'),
        ),
        migrations.AlterField(
            model_name='study',
            name='metric',
            field=models.ForeignKey(default='SimpleFunction', on_delete=django.db.models.deletion.CASCADE, to='API.Metric', to_field='name'),
        ),
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='trial',
            name='status',
            field=models.CharField(default='Pending', max_length=128),
        ),
    ]
