# Generated by Django 3.0.2 on 2020-03-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='dataset',
            field=models.ForeignKey(default='iris', on_delete=django.db.models.deletion.CASCADE, to='API.Dataset', to_field='name'),
        ),
    ]
