# Generated by Django 3.0.2 on 2020-03-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20200305_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='parameter_values',
            new_name='parameters',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='name',
        ),
    ]
