# Generated by Django 3.0.2 on 2020-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20200305_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='training_step',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
