# Generated by Django 3.0.2 on 2020-03-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20200305_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrialMetric',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='study',
            new_name='study_name',
        ),
        migrations.AddField(
            model_name='trial',
            name='score_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.CharField(choices=[('DISCRETE', 'Discrete'), ('CATEGORICAL', 'Categorical'), ('FLOAT', 'Float'), ('INTEGER', 'Integer')], max_length=128),
        ),
        migrations.AlterField(
            model_name='study',
            name='objective',
            field=models.CharField(choices=[('MAXIMIZE', 'Maximize'), ('MINIMIZE', 'Minimize')], max_length=128),
        ),
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(default='PENDING', max_length=128),
        ),
        migrations.AlterField(
            model_name='trial',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped')], max_length=128),
        ),
    ]
