# API version
openapi: "3.0.0"

# Info on version of software
info:
  description: "Suggestion API for creating and querying Ahmet's studies"
  version: "0.1"
  title: "Ahmet API"
  contact:
    email: "andrea.cors95@gmail.com"

# On which server/host is available the app
servers:
  - url: http://localhost:8080/suggestions/v0.1
    description: Development server API v0.1

tags:
  - name: "studies"
    description: "Manage the studies"
  - name: "algorithms"
    description: "Manage the algorithms"
  - name: "trials"
    description: "Manage the trials"
  - name: "actions"
    description: "Get, update and delte entities"

# Define the paths to resources 
paths:
  /studies:
    get:
      tags:
        - "studies"
      description: Return a list with all the studies.
      responses:
        200:
          description: RGB values of the required color
          content:
            # I can list many returned formats, the distinction is base on Accept field of request
            application/json:
              schema:    # You'll find it down in file
                $ref: '#/components/schemas/ColorResponse'
        400:
          description: Invalid input parameters
    post:
      tags:
        - "studies"
      description: Create a new study
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Color'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfirmEmptyMessage"
        400:
          description: Invalid input parameters
        409:
          description: Color already exists
  /algorithms:
    get:
      tags:
        - "algorithms"
      description: Return the list of all available algorithms.
      responses:
        200:
          description: RGB values of the required color
          content:
            # I can list many returned formats, the distinction is base on Accept field of request
            application/json:
              schema:    # You'll find it down in file
                $ref: '#/components/schemas/ColorResponse'
        400:
          description: Invalid input parameters
    post:
      tags:
        - "algorithms"
      description: Insert a new algorithm
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Color'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfirmEmptyMessage"
        400:
          description: Invalid input parameters
        409:
          description: Color already exists
  /trials:
    get:
      tags:
        - "trials"
      description: Return all the stored trials.
      responses:
        200:
          description: RGB values of the required color
          content:
            # I can list many returned formats, the distinction is base on Accept field of request
            application/json:
              schema:    # You'll find it down in file
                $ref: '#/components/schemas/ColorResponse'
        400:
          description: Invalid input parameters
  /{study_name}:
    parameters:
      - name: study_name
        in: path	 # the name variable is on path
        required: true
        description: The name of the study.
        schema:
          type: string
    # Here I list the available methods (get, post, put , ...)
    get:
      tags:
        - "actions"
      description: Return information about a study.
      responses:
        200:
          description: RGB values of the required color
          content:	
	  # I can list many returned formats, the distinction is base on Accept field of request 
            application/json:
              schema: 	# You'll find it down in file
                $ref: '#/components/schemas/ColorResponse'
        400:
          description: Invalid input parameters
    put:
      tags:
        - "actions"
      description: Update an existing study status.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Color'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfirmEmptyMessage"
        400:
          description: Invalid input parameters
        404:
          description: Color does not exist
    delete:
      tags:
        - "actions"
      description: Delete a study.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfirmEmptyMessage"
        400:
          description: Invalid input parameters
        409:
          description: Color already exists
  /{study_name}/{trial_id}:
    parameters:
      - name: study_name
        in: path     # the name variable is on path
        required: true
        description: The name of the study.
        schema:
          type: string
      - name: trial_id
        in: path     # the name variable is on path
        required: true
        description: The identifier of the trial.
        schema:
          type: string
    # Here I list the available methods (get, post, put , ...)
    get:
      tags:
        - "actions"
      description: Return information about a specific trial of a study.
      responses:
        200:
          description: RGB values of the required color
          content:
            # I can list many returned formats, the distinction is base on Accept field of request
            application/json:
              schema:    # You'll find it down in file
                $ref: '#/components/schemas/ColorResponse'
        400:
          description: Invalid input parameters
    put:
      tags:
        - "actions"
      description: Update an existing trial of a study.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Color'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfirmEmptyMessage"
        400:
          description: Invalid input parameters
        404:
          description: Color does not exist
    delete:
      tags:
        - "actions"
      description: Delete a the trial.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfirmEmptyMessage"
        400:
          description: Invalid input parameters
        409:
          description: Color already exists
  /{study_name}/{trial_id}/{metric_id}:
    parameters:
      - name: study_name
        in: path     # the name variable is on path
        required: true
        description: The name of the study.
        schema:
          type: string
      - name: trial_id
        in: path     # the name variable is on path
        required: true
        description: The identifier of the trial.
        schema:
          type: string
      - name: metric_id
        in: path     # the name variable is on path
        required: true
        description: The identifier of the metric.
        schema:
          type: string
    # Here I list the available methods (get, post, put , ...)
    get:
      tags:
        - "actions"
      description: Return information about the study metric.
      responses:
        200:
          description: RGB values of the required color
          content:
            # I can list many returned formats, the distinction is base on Accept field of request
            application/json:
              schema:    # You'll find it down in file
                $ref: '#/components/schemas/ColorResponse'
        400:
          description: Invalid input parameters
    put:
      tags:
        - "actions"
      description: Update an existing metric.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Color'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfirmEmptyMessage"
        400:
          description: Invalid input parameters
        404:
          description: Color does not exist
    delete:
      tags:
        - "actions"
      description: Delete a the metric.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfirmEmptyMessage"
        400:
          description: Invalid input parameters
        409:
          description: Color already exists

components:
  schemas:
    Algorithm:
      type: object
      properties:
        message:
          type: string
          format: string
          description: Request executed successfully
    Study:
      type: integer
      format: int32
      minimum: 0
      maximum: 255
      description: Color component
    Parameter:
      type: object
      properties:
        r:
          $ref: '#/components/schemas/ColorComponent'
        b:
          $ref: '#/components/schemas/ColorComponent'
        g:
          $ref: '#/components/schemas/ColorComponent'
    Trial:
      type: object
      properties:
        message:
          type: string
          format: string
          description: Confirm color retrieval.
        data:
          $ref: '#/components/schemas/Color'
    TrialMetric:
      type: object

