# API version
openapi: "3.0.0"

# Info on version of software
info:
  version: "0.1"
  title: "Colors API"

# On which server/host is available the app
servers:
# BasePath is replaced by the info given below (in this case the final url: /api/v0.1)
  - url: /{basePath}
    description: Current server
    variables:
      basePath:
        default: 'api/v0.1'

# Define the paths to resources 
paths:
  /color/{name}:
    parameters:
      - name: name
        in: path	 # the name variable is on path
        required: true
        description: The name of the color.
        schema:
          type: string
    # Here I list the available methods (get, post, put , ...)
    get:
      description: Return the color registered with the given name.
      responses:
        200:
          description: RGB values of the required color
          content:	
	  # I can list many returned formats, the distinction is base on Accept field of request 
            application/json:
              schema: 	# You'll find it down in file
                $ref: '#/components/schemas/ColorResponse'
        400:
          description: Invalid input parameters
    post:
      description: Insert a new color
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Color'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfirmEmptyMessage"
        400:
          description: Invalid input parameters
        409:
          description: Color already exists
    put:
      description: Update an existing color
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Color'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfirmEmptyMessage"
        400:
          description: Invalid input parameters
        404:
          description: Color does not exist


components:
  schemas:
    ConfirmEmptyMessage:
      type: object
      properties:
        message:
          type: string
          format: string
          description: Request executed successfully
    ColorComponent:
      type: integer
      format: int32
      minimum: 0
      maximum: 255
      description: Color component
    Color:
      type: object
      properties:
        r:
          $ref: '#/components/schemas/ColorComponent'
        b:
          $ref: '#/components/schemas/ColorComponent'
        g:
          $ref: '#/components/schemas/ColorComponent'
    ColorResponse:
      type: object
      properties:
        message:
          type: string
          format: string
          description: Confirm color retrieval.
        data:
          $ref: '#/components/schemas/Color'

